### ISSUE TITLE
VPN issues

### ISSUE THREAD

**Issue by 20040520xy** [Loli-Killer/ArknightsCrisisSimulator#1]
Hi, I am an CN player of Arknights. I have a friend who have an account on the EN server. Recently I've been trying to use the Crisis Simulator, but the program keep failing, and telling me that I can't connect www.google.com:443, 502 Bad Gateway 57b, I wonder if it is because that I'm China? I did use Clash to connect VPN, but there's still no use.

**Comment by Loli-Killer** [comment]
The `www.googleapi.com:443 502 Bad Gateway 73b` error happens because of the proxy setup and should not prevent you from playing Arknights. Try ignore and login into Arknights and see.
